### PR TITLE
add new sequence classifier recipe

### PR DESCRIPTION
**Pull request by gregcaporaso**
**NOT READY FOR MERGE**

Still needs text...

### CODE REVIEW

**Comment by jairideout** [comment]
Can you update the filename to match the naming conventions we're using for other recipes?

**Comment by gregcaporaso** [comment]
Will do before merge, still just hacking on this.

**Comment by wasade** [comment]
This is awesome... can't wait to watch the presentation!!

**Comment by jairideout** [comment]
Closing as many of the techniques in this recipe are now in the "creating a region-specific reference collection" recipe (#66).

**Pull request closed without merging**
