### PR TITLE
BUG: fixed variable name typos

### PR DESCRIPTION
**Pull request by williamrowell**
Variable name mean_nonbiologial_sequence_length was used twice, instead
of mean_nonbiological_sequence_length and
std_nonbiological_sequence_length.  Later, non_biologial_sequence was
used instead of non_biological_sequence.  Fixed for clarity.

### CODE REVIEW

**Comment by jairideout** [comment]
@williamrowell thanks for the fixes! Sorry that this slipped by -- if you reopen the PR I'll merge it.

**Comment by jairideout** [comment]
Nevermind, found a way to reopen. Thanks again!

**Comment by williamrowell** [comment]
Glad I could help.  Not sure why it didn't pass the tests.  Thanks for all of the great work!

**Comment by jairideout** [comment]
I think the test suite is currently broken (not related to your changes). We'll work on fixing that within the next couple weeks when we update the cookbook to use the upcoming scikit-bio beta release.

**Pull request merged**
